### ISSUE TITLE
Support to aditional html tags

### ISSUE THREAD

**Issue by joassouza** [JohnMcLear/ep_better_pdf_export#1]
Hey @JohnMcLear , I'm working in a feature to export to pdf. I've some troubles because my pad has custom markup. As far I know, abiword doesn't have support to it.
Do you have any ideia how to solve it?

**Comment by JohnMcLear** [comment]
@joassouza I'd need to look at your project, I'm available as a gun for hire if you want to email me please do..

RE this issue.  It's in the wrong place as better pdf export doesn't use abiword.
