### ISSUE TITLE
Missing html-pdf

### ISSUE THREAD

**Issue by meaz** [JohnMcLear/ep_better_pdf_export#7]
I have etherpad-lite 1.7.5.

In the logs, I can see this:
```
Apr 17 04:44:39 debian10 run.sh[17102]: #033[31m[2020-04-17 04:44:39.113] [ERROR] console - #033[39mFailed to load '/var/www/etherpad-lite/node_modules/ep_better_pdf_export/export.js' for 'ep_better_pdf_export/ep_better_pdf_export/hooks/exportConvert': Error: Cannot find module './node_modules/html-pdf'
```

Shouldn't this be automatically installed?

**Comment by diegorodridev** [comment]
I am having the same problem. I have even tried to install html-pdf in parallel but with no luck. The library is there, but the same error is triggering.

It is strange as in the package.json of the ep_better_pdf_export package, html-pdf is indeed included in its latest version:

` "dependencies": {
    "html-pdf": "2.2.0",
    "request": ">=2.67.0"
  },
`
Any ideas?

**Comment by JohnMcLear** [comment]
I am killing this plugin.  

1. It has a security vulnerability that hasn't been patched.
2. It doesn't provide anything we can't properly solve within Etherpad.
3. Etherpad's internal export functionality is a lot better (and will be even better in 1.9).
4. It was an inefficient way of generating PDF from HTML compared to Libreoffice.

Updated README and unpublished from npmjs
